### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Prannov**
The project classifies with 95.7 % accuracy

### CODE REVIEW

**Comment by Prannov** [comment]
Please merge my project. The accuracy of the classification is 95.7%.

**Review by sarthakpant772 — CHANGES_REQUESTED** [review]
Please insert it inside submission file @Prannov .

**Comment by Prannov** [comment]
The submissions file is missing when I fork the repo.

**Comment by Prannov** [comment]
What is the other alternative as the submissions file is not visible when I fork the repo?

**Comment by sarthakpant772** [comment]
@Prannov  try using fetch upstream in your forked repo

**Comment by Prannov** [comment]
I have added my project to the submissions file. Please merge it.

**Comment by sarthakpant772** [comment]
great @Prannov

**Pull request merged**
