### PR TITLE
Getting best train-test split value

### PR DESCRIPTION
**Pull request by sagnik1511**
This PR contributes to #4.

### Improvements:

Previous results having train-test split as `0.7` shared the test accuracy of `0.8722`. But the new notebook was executed using `0.15`  test split and found the accuracy to be improved than previous which is `0.88125`.

Do share if any update is needed or not :)

### CODE REVIEW

**Comment by sarthakpant772** [comment]
hey @sagnik1511  make your changes in different file . Like copy the data u want and make a new file under submission.

**Comment by sagnik1511** [comment]
So, basically, I have to create another notebook with updates and save it alongside the original one?

**Comment by sarthakpant772** [comment]
yes @sagnik1511 save that in submission folder as written in readme

**Comment by sagnik1511** [comment]
Do check, I've updated the PR

**Review by sarthakpant772 — APPROVED** [review]
@sagnik1511  great work

**Comment by sagnik1511** [comment]
also, one thing, isn't this PR going to be labelled hacktoberfestaccepted?

**Pull request merged**
